FROM centos/systemd
#ENV container docker
RUN yum update -y \
&& yum install -y sudo \ 
wget \ 
which \ 
passwd \
&& yum clean all
COPY setup-mapr-setup.sh /
RUN ["chmod", "+x", "/setup-mapr-setup.sh"]
STOPSIGNAL SIGRTMIN+3
CMD [ "/sbin/init" ]
#ENTRYPOINT /sbin/init ; /setup-mapr-setup.sh
